"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# 放置要执行py的列表
APP = ['convert.py']

# 放置要打包的资源文件列表
DATA_FILES = ['logo.icns']

# 其他配置
OPTIONS = {
    'iconfile': 'logo.icns',
    'plist': {
                    'CFBundleName'   : 's2t',     # 应用名
                    'CFBundleDisplayName': 's2t', # 应用显示名
                    'CFBundleVersion': '2.5.3',      # 应用版本号
                    'CFBundleIdentifier' : 's2t', # 应用包名、唯一标识
                    'NSHumanReadableCopyright': 'Copyright © 2024 GUO.LIMIN. All rights reserved.', # 可读版权
    },
    'includes': ['python-docx', 'opencc-python-reimplemented'],
}


setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
